# Generated by Django 3.2.9 on 2021-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poromot',
            field=models.BooleanField(default=False),
        ),
    ]
