# Generated by Django 3.2.9 on 2021-11-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_article_poromot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='poromot',
            new_name='poromote',
        ),
    ]
